package bc.bg.tools.chronos.endpoint.ui.tab.reporting;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.layout.VBox;

public class RecentReportActionPanelController {
    @FXML
    private VBox actionButtonGeneratedContainer;
    @FXML
    private Button btnReprintRecentReport;
    @FXML
    private Button btnRedoRecentReport;
    @FXML
    private Button btnDeleteRecentReport;

    // Event Listener on Button[#btnReprintRecentReport].onAction
    @FXML
    public void reprintRecentReport(ActionEvent event) {
	// TODO Autogenerated
    }

    // Event Listener on Button[#btnRedoRecentReport].onAction
    @FXML
    public void redoRecentReport(ActionEvent event) {
	// TODO Autogenerated
    }

    // Event Listener on Button[#btnDeleteRecentReport].onAction
    @FXML
    public void eleteRecentReport(ActionEvent event) {
	// TODO Autogenerated
    }

    @FXML
    public void deleteRecentReport() {
	// TODO Autogenerated
    }
}
