package bc.bg.tools.chronos.endpoint.ui.tab.reporting;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class ReportActionPanelController {
    @FXML
    private Button btnPrepareReport;
    @FXML
    private Button btnClearReportSettings;
    @FXML
    private Button btnSaveReportSettingsAsPreset;

    // Event Listener on Button[#btnPrepareReport].onAction
    @FXML
    public void prepareReport(ActionEvent event) {
	// TODO Autogenerated
    }

    // Event Listener on Button[#btnClearReportSettings].onAction
    @FXML
    public void clearReportSettings(ActionEvent event) {
	// TODO Autogenerated
    }

    // Event Listener on Button[#btnSaveReportSettingsAsPreset].onAction
    @FXML
    public void saveReportSettings(ActionEvent event) {
	// TODO Autogenerated
    }
}
