package bc.bg.tools.chronos.endpoint.ui.tab.reporting;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.control.ComboBox;

import javafx.scene.control.CheckBox;

import javafx.scene.control.DatePicker;

public class ReportingController {
    @FXML
    private ListView listViewRecentReports;
    @FXML
    private Button btnHideRecentReports;
    @FXML
    private Button btnShowRecentReports;
    @FXML
    private TextField txtFieldSelectedTemplateDoc;
    @FXML
    private Button btnOpenTemplateFile;
    @FXML
    private ComboBox comboBoxReportPreset;
    @FXML
    private Button btnApplyPreset;
    @FXML
    private DatePicker datePickerReportFrom;
    @FXML
    private DatePicker datePickerReportTo;
    @FXML
    private CheckBox checkBoxIncludeEffort;
    @FXML
    private CheckBox checkBoxIncludeFinancial;
    @FXML
    private CheckBox checkBoxIncludeStatistics;
    @FXML
    private DatePicker datePickerReportPresetFrom;
    @FXML
    private Button btnApplyPresetFromDate;
    @FXML
    private DatePicker datePickerReportPresetTo;
    @FXML
    private Button btnApplyPresetToDate;
    @FXML
    private CheckBox checkBoxPresetIncludeEffort;
    @FXML
    private Button btnApplyPresetIncludeEffort;
    @FXML
    private CheckBox checkBoxPresetIncludeFinancial;
    @FXML
    private Button btnApplyPresetIncludeFinancial;
    @FXML
    private CheckBox checkBoxPresetIncludeStatistics;
    @FXML
    private Button btnApplyPresetIncludeStatistics;

    // Event Listener on Button[#btnHideRecentReports].onAction
    @FXML
    public void hideRecentReports(ActionEvent event) {
	// TODO Autogenerated
    }

    // Event Listener on Button[#btnShowRecentReports].onAction
    @FXML
    public void showRecentReports(ActionEvent event) {
	// TODO Autogenerated
    }

    // Event Listener on Button[#btnOpenTemplateFile].onAction
    @FXML
    public void openTemplateFile(ActionEvent event) {
	// TODO Autogenerated
    }

    // Event Listener on Button[#btnApplyPreset].onAction
    @FXML
    public void applyPreset(ActionEvent event) {
	// TODO Autogenerated
    }

    // Event Listener on Button[#btnApplyPresetIncludeStatistics].onAction
    @FXML
    public void applyPresetSetting(ActionEvent event) {
	// TODO Autogenerated
    }
}
